### ISSUE TITLE
16bit color depth support please?

### ISSUE THREAD

**Issue by taskx6004** [hra1129/ShaRPIKeebo-customize-for-japanese#1]
Hi, newer kernel now has no frame buffer option for 32bit depth, after some try and error with modifying your code I could not hack it to make it work on a recent 16bit depth only OS. Would you kindly update your code?

**Comment by hra1129** [comment]
Ok.
After we finish the audio-related work we are currently working on, we will Consider 16-bit color depth support.

**Comment by hra1129** [comment]
First, only sharpikeebo_lcd is now 16bpp compliant.
Can you please check if this works without any problem?
If it works fine, we will implement the same fix for sharpikeebo_glib.

**Comment by taskx6004** [comment]
Sorry screen could talk to SPI but not rendering correctly. I guess you have forgot to modify RGB8888 -> to RGB565 in the pixel converting function, if 16bit depth is RGB565.

**Comment by hra1129** [comment]
I reinstalled the latest version of RaspberryPiOS Lite 32bit and tried it and it worked fine.

In /boot/config.txt, I need to set framebuffer to 400x240 size and disable dtoverlay=vc4-kms-v3d.
I have specified how to modify config.txt.

https://github.com/hra1129/ShaRPIKeebo-customize-for-japanese/blob/main/sharp_memory_display/readme_en.txt

**Comment by taskx6004** [comment]
Sorry didn't notice dt part needs some modification

**Comment by hra1129** [comment]
Please let me know if it works.😉
